# -*- coding: utf-8 -*-


class RemoveEmptyLinesMiddleware(object):
    def process_response(self, request, response):
        # Skip admin
        if request.path.startswith('/admin'):
            return response

        # Only process HTML pages generated by our application
        if response.status_code == 200:
            if response["content-type"].startswith("text/html"):
                response.content = '\n'.join([s for s in response.content.splitlines() if s.strip()])

        return response
